### ISSUE TITLE
Optional part of step 1 does not work

### ISSUE THREAD

**Issue by andrea-vandin** [HPI-Information-Systems/TimeEval-algorithms#12]
Hello, when executing  
- docker tag registry.gitlab.hpi.de/akita/i/python3-base:latest registry.gitlab.hpi.de/akita/i/python3-base:0.2.5

I get this error message:
- Error response from daemon: No such image: registry.gitlab.hpi.de/akita/i/python3-base:latest

This prevents me from succeeding in the remaining steps. I tried both for LOF and COF.

Can you help me on this?

**Comment by CodeLionX** [comment]
tl;dr

```sh
docker tag registry.gitlab.hpi.de/akita/i/python3-base:0.2.5 registry.gitlab.hpi.de/akita/i/python3-base:latest
```

---

Hi @andrea-vandin,

I can reproduce the issue. Thank you for reporting!

It appears that we interchanged the arguments to `docker tag`:

```sh
$ docker tag --help

Usage:  docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]

Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
```

We first have to supply the `:0.2.5` (source) tag and then the `:latest` (target) tag. Please try again with:

```sh
docker tag registry.gitlab.hpi.de/akita/i/python3-base:0.2.5 registry.gitlab.hpi.de/akita/i/python3-base:latest
```

**Comment by CodeLionX** [comment]
Assuming the issues was resolved. If there are still problems building the images, please re-open this issue.
