### ISSUE TITLE
check is needed to ensure the algorithm is not used for multi-variate dataset by eliminative the remaining columns. 

### ISSUE THREAD

**Issue by DhavalRepo18** [HPI-Information-Systems/TimeEval-algorithms#6]
The following line makes the proposed algorithm work for multi-variate cases by selecting the first column. 

https://github.com/HPI-Information-Systems/TimeEval-algorithms/blob/92d7e1b4be55d204174efd6705ee100c0acd8e80/dwt_mlead/algorithm.py#L46

**Comment by CodeLionX** [comment]
Yes, our version of DWT-MLEAD can be executed on a selected channel of a multivariate dataset (with the parameter `use_column_index`). This allows us to experiment with different configurations and is on purpose. We want to avoid being overly restrictive regarding the usage of the algorithms (and their Docker images).

TimeEval, however, will automatically avoid such executions if `skip_invalid_combinations=True` (which is the default), see https://timeeval.readthedocs.io/en/latest/concepts/configuration.html#avoiding-conflicting-combinations.
