### ISSUE TITLE
Left align - 

### ISSUE THREAD

**Issue by DhavalRepo18** [HPI-Information-Systems/TimeEval-algorithms#7]
https://github.com/HPI-Information-Systems/TimeEval-algorithms/tree/92d7e1b4be55d204174efd6705ee100c0acd8e80/phasespace_svm

Technically, right align is correct that at a time point "t", you leveraged only the info that is available at "t" or prior to "t". It will not be as good as Left align as the labeling is a little srtickt.

**Comment by wenig** [comment]
Hi Dhaval,

The algorithm slides a context window (from left to right) over the time series and calculates the anomaly score for the subsequence that it currently looks at. Now, the difference between Left- and Right-Align is that this context window is either filled from the left or from the right. Bear in mind that we do not score single points in the time series but subsequences. For finding anomalies, left align is better, as seen in the plots. If we think about streaming scenarios, of course this would give us a score for a certain position only when the entire context window slid across this position. However, streaming is not our focus.

Does this solve your issue? Do you suggest some code or documentation changes? If so, please specify them!

**Comment by DhavalRepo18** [comment]
The definition of anomaly score is not very clear w.r.t. the time point say "t".  Let me thing about it. 

The paper http://vldb.org/pvldb/vol15/p1779-wenig.pdf has very good results for the Pharse-SVM due to the preference of one alignment over the other.

**Comment by wenig** [comment]
For the definition of "anomaly score", please have a look at Definition 2.2 in [the paper](http://vldb.org/pvldb/vol15/p1779-wenig.pdf). 

Also from [the paper](http://vldb.org/pvldb/vol15/p1779-wenig.pdf):

> For algorithms that score entire subsequences 𝑇𝑖,𝑗 , we assign the subsequence score to all 𝑇𝑘 ∈ 𝑇𝑖,𝑗 . If data points receive subsequence scores from multiple overlapping subsequences, which is when they are part of overlapping subsequences, we assign the average of these scores as individual point scores (maximum aggregation performed worse).

That means, no matter if we are using left align or right align, each single point of the time series receives an anomaly score, which is the average of all window scores that this single point is contributing to. That way, left align and right align have similar anomaly scores.

**Comment by DhavalRepo18** [comment]
@wenig Thanks for your explanation. But if left and right align perform similarly, after conducting reverse-windowing then it should be mentioned in the algorithm description.
