### ISSUE TITLE
An error occurs when building the algorithm image.

### ISSUE THREAD

**Issue by JeonghwaYoo-R** [HPI-Information-Systems/TimeEval-algorithms#9]
When I building the algorithm image, this error occurs.

`docker build -t registry.gitlab.hpi.de/akita/i/lof ./lof`

> [+] Building 1.7s (3/3) FINISHED
>  => [internal] load build definition from Dockerfile                                                               0.0s
>  => => transferring dockerfile: 38B                                                                                0.0s
>  => [internal] load .dockerignore                                                                                  0.0s
>  => => transferring context: 2B                                                                                    0.0s
>  => ERROR [internal] load metadata for registry.gitlab.hpi.de/akita/i/pyod:0.2.5                                   1.6s
> ------
>  > [internal] load metadata for registry.gitlab.hpi.de/akita/i/pyod:0.2.5:
> ------
> failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 403 Forbidden

How can I solve this problem?

**Comment by CodeLionX** [comment]
Docker can't find the base image of LOF. You need to build and tag the `registry.gitlab.hpi.de/akita/i/pyod:0.2.5` image first:

```bash
docker build -t registry.gitlab.hpi.de/akita/i/python3-base ./0-base-images/python-3-base
docker build -t registry.gitlab.hpi.de/akita/i/pyod:0.2.5 ./0-base-images/pyod
docker build -t registry.gitlab.hpi.de/akita/i/lof ./lof
```

You can find the base image dependencies in the [big overview table](https://github.com/HPI-Information-Systems/TimeEval-algorithms#overview) in the README of this repository.

**Comment by JeonghwaYoo-R** [comment]
Thank you for your reply! I solved this problem! 

However, there is one strange thing.
When I read the README and built the pyod, it failed.

`docker build -t registry.gitlab.hpi.de/akita/i/python3-base:0.2.5 ./python3-base` -> Success
`docker build -t registry.gitlab.hpi.de/akita/i/pyod:0.2.5 ./pyod)` -> Failed

> [+] Building 2.0s (3/3) FINISHED
>  => [internal] load build definition from Dockerfile                                                               0.1s
>  => => transferring dockerfile: 508B                                                                               0.0s
>  => [internal] load .dockerignore                                                                                  0.0s
>  => => transferring context: 2B                                                                                    0.0s
>  => ERROR [internal] load metadata for registry.gitlab.hpi.de/akita/i/python3-base:latest                          1.9s


Did it fail by building with python3-base:0.2.5 instead of latest?
Anyway, my problem was solved thanks to you. Thank you!

**Comment by CodeLionX** [comment]
> Did it fail by building with python3-base:0.2.5 instead of latest?

Yes, exactly.

This would not be a problem, if you had access to our registry. But, unfortunately, we cannot give everyone access to our internal Docker registry.
